version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      target: frontend
    command: npm run dev -- --host  
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
